### PR TITLE
fix: use mask to handle linglong

### PR DESCRIPTION
**Pull request by Decodetalkers**
linglong is enabled in etc, so here use mask instead

Issue: https://github.com/linuxdeepin/developer-center/issues/6440
Log:

### CODE REVIEW

**Comment by black-desk** [comment]
> linglong is enabled in etc, so here use mask instead
> 
> Issue: [linuxdeepin/developer-center#6440](https://github.com/linuxdeepin/developer-center/issues/6440) Log:

少了一个回车 Log: 应该在下一行

**Comment by Decodetalkers** [comment]
> > linglong is enabled in etc, so here use mask instead
> > 
> > Issue: [linuxdeepin/developer-center#6440](https://github.com/linuxdeepin/developer-center/issues/6440) Log:
> 
> 少了一个回车 Log: 应该在下一行

这个是GitHub自动填充的结果（

**Review by black-desk — APPROVED** [review]

**Review by kegechen — APPROVED** [review]

**Pull request merged**
