### PR TITLE
fix: modify transparent text

### PR DESCRIPTION
**Pull request by FeiWang1119**
modify transparent text

Issue: https://github.com/linuxdeepin/developer-center/issues/8543

### CODE REVIEW

**Comment by FeiWang1119** [comment]
截图_选择区域_20240513134811

**Review by kegechen — APPROVED** [review]
不透明度

**Comment by FeiWang1119** [comment]
截图_选择区域_20240513150351

**Review by kegechen — DISMISSED** [review]

**Review by kegechen — APPROVED** [review]

**Review by kegechen — APPROVED** [review]

**Pull request merged**
