### PR TITLE
feat: use DIconTheme::findQIcon

### PR DESCRIPTION
**Pull request by kegechen**
Find QIcon from name without relying on platform(theme) plugins, e.g dde-qt5integration dde-qt5xcb-plugin.

Replacing QIcon::fromTheme.

Issue: https://github.com/linuxdeepin/developer-center/issues/4112

### CODE REVIEW

**Comment by wineee** [comment]
image
Some icon is still black


test on https://github.com/linuxdeepin/dde-nixos/pull/14

**Comment by BLumia** [comment]
> Some icon is still black
> 
> test on [linuxdeepin/dde-nixos#14](https://github.com/linuxdeepin/dde-nixos/pull/14)

Did you cleared the icon cache? (remove all files under `~/.cache/deepin/icons`)

**Comment by wineee** [comment]
> > Some icon is still black
> > 
> > test on [linuxdeepin/dde-nixos#14](https://github.com/linuxdeepin/dde-nixos/pull/14)
> 
> Did you clear the icon cache? (remove all files under `~/.cache/deepin/icons`)

I removed all cache in '~/.cache/deepin'

**Comment by kegechen** [comment]
> image Some icon is still black
> 
> test on [linuxdeepin/dde-nixos#14](https://github.com/linuxdeepin/dde-nixos/pull/14)

this commit has nothing to do with the black icon. 
see https://github.com/linuxdeepin/dtkgui/pull/198

**Comment by zccrs** [comment]
/+1

**Review by Decodetalkers — APPROVED** [review]

**Review by BLumia — APPROVED** [review]

**Pull request merged**
