### PR TITLE
fix CMake Error at CMakeLists.txt:39 (if):

### PR DESCRIPTION
**Pull request by FirstLoveLife**
```
chenli% cmake --version         
cmake version 3.15.20190810-g32a7605

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
if given arguments:

    "STREQUAL" "Debug"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!

### CODE REVIEW

**Comment by BLumia** [comment]
Hi and thanks for the patch!

We are moved to a internal GitLab instance for a while, but it's not ready for public. The internal working branch is also have a lots of commits ahead of the GitHub master branch, so sorry we cannot review and merge your patch now :(

We will resume review and merge community patches as soon as we are ready, and thanks again for your patch <3

**Comment by FirstLoveLife** [comment]
> We are moved to a internal GitLab instance for a while, but it's not ready for public. The internal working branch is also have a lots of commits ahead of the GitHub master branch, so sorry we cannot review and merge your patch now :(

Well, fail enough, however, as a deepin worker, can i be accessible to deepin's internal gitlab?

**Comment by BLumia** [comment]
Not sure if there are any plan to make the GitLab instance public accessable. cc @hualet

**Comment by justforlxz** [comment]
Hello, we have improved the synchronization between the private warehouse and github. Since the master branch has been changed to uos, I suggest you resubmit the merge request on the uos branch.

**Pull request closed without merging**
