### PR TITLE
chore: not delete length of the final spacing

### PR DESCRIPTION
**Pull request by Decodetalkers**
when caculate the lenght of the left listview, before the final spacing is deleted, now not delete it

Log:

### CODE REVIEW

**Comment by Decodetalkers** [comment]
https://github.com/linuxdeepin/developer-center/issues/5180

**Review by BLumia — APPROVED** [review]
确认验证修复了再合

**Comment by Decodetalkers** [comment]
> 确认验证修复了再合

这个应该是没有问题的

**Pull request merged**
