### PR TITLE
feat: 调整指纹录入提示

### PR DESCRIPTION
**Pull request by ECQZXC**
修改指纹录入状态提示

Log: 调整指纹录入提示
Task: https://pms.uniontech.com/task-view-198139.html
Influence: 指纹录入
Change-Id: I9d0c34be46f590d08982f50b0298ee72e3972570

### CODE REVIEW

**Comment by ECQZXC** [comment]
check check_job/archlinux-build

**Review by waterlovemelon — APPROVED** [review]

**Review by chenjun1982 — APPROVED** [review]

**Pull request merged**
