### PR TITLE
fix: focus color stay

### PR DESCRIPTION
**Pull request by Decodetalkers**
resolve:https://github.com/linuxdeepin/developer-center/issues/3624

### CODE REVIEW

**Comment by hudeng-go** [comment]
/+1

**Review by BLumia — DISMISSED** [review]

**Comment by BLumia** [comment]
image

从网页点更新时记得从下拉里选 rebase，不然会导致这种提交混进来。

**Review by FeiWang1119 — APPROVED** [review]

**Comment by kegechen** [comment]
dtk改

**Pull request closed without merging**
